export const SELECTORS = {
  container: '.main-content',
  searchInput: '#search-input',
  slider: '.slider',
  sliderSlide: '.slider__slide',
  sliderContainer: '.slider__container',
  slidesContainer: '#slides-container',
  sliderBtn: '.slider__btn',
  sliderPrevBtn: '#slide-arrow-prev',
  sliderNextBtn: '#slide-arrow-next',
  slideContainer: '#slides-container',
  modalContent: '.modal__content',
  closeModalBtn: '#close-modal-btn',
  cardContainer: '.card',
  dialog: 'dialog',
  cardImg: '.card-img',
  goodsCardContent: '.main-content__cards',
  goodsTitle: '.main-content__title',
  basketIcon: '#header__basket',
  basketSum: '#basket__sum',
  plusBasketBtn: 'plus',
  minusBasketBtn: 'minus',
  footerAccordion: '.accordion-button',
  scrollTopBtn: '.scroll-top',
  showMoreBtn: '#show-more'
}
